
# Server Configuration
server:
  port: 8080

# Spring Application
spring:
  application:
    name: pay-system

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

  # ===============================
  # DATABASE (MySQL) SETTINGS
  # ===============================
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:paysystem}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:payuser}
    password: ${MYSQL_PASSWORD:paypassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Flyway will manage the schema, so hibernate should only validate it
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true # If the schema already exists, Flyway will create a baseline
    locations: classpath:db/migration
    user: ${MYSQL_ROOT_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:root}

  # ===============================
  # REDIS SETTINGS
  # ===============================
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}

  # ===============================
  # MONGODB SETTINGS
  # ===============================
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:paysystem_logs}
      username: ${MONGO_ROOT_USER:admin}
      password: ${MONGO_ROOT_PASSWORD:admin123}
      authentication-database: admin

  # ===============================
  # ELASTICSEARCH SETTINGS
  # ===============================
  elasticsearch:
    uris:
      - http://${ES_HOST:localhost}:${ES_PORT:9200}

  # ===============================
  # KAFKA SETTINGS
  # ===============================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
